[build-system]
requires = ["setuptools >= 65", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "CTLearn"
description = "CTLearn is a package under active development to run deep learning models to analyze data from all major current and future arrays of imaging atmospheric Cherenkov telescopes (IACTs)."
readme = "README.rst"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Ari Brill"},
    {name = "Bryan Kim"},
    {name = "Tjark Miener"},
    {name = "Daniel Nieto", email = "d.nieto@ucm.es"}
]

classifiers = [
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

]

requires-python = ">=3.12"
dependencies = [
    "astropy",
    "ctapipe[all]>=0.29",
    "dl1_data_handler>=0.14.8",
    "numba",
    "numpy",
    "pandas",
    "pip",
    "pydot",
    "pytorch-lightning",
    "pyyaml",
    "scikit-learn",
    "setuptools",
    "tensorboard",
    "tensorflow>=2.16",
    "torch>=2.4.0",
    "torchvision",
    "torchmetrics",
    "opencv-python",
]

dynamic = ["version"]

[tool.setuptools]
packages = ["ctlearn"]

[project.optional-dependencies]

# all is with all optional *runtime* dependencies
# use `dev` to get really all dependencies
all = [
    "matplotlib ~=3.0",
    "pyirf ~=0.14.0",
]

tests = [
    # at the moment, essentially all tests rely on test data from simtel
    # it doesn't make sense to skip all of these.
    "ctlearn",
    "pytest >=9.0",
    "pytest-cov",
    "pytest-xdist",
    "pytest_astropy_header",
]

docs = [
  "sphinx",
  "sphinx-rtd-theme",
]

dev = [
    "ctlearn[all,docs,tests]",
    "setuptools_scm[toml]",
]

[project.urls]
repository = "https://github.com/ctlearn-project/ctlearn"
documentation = "https://ctlearn.readthedocs.io/en/latest/"

[project.scripts]
ctlearn-train-keras-model = "ctlearn.tools.keras.train_model:main"
ctlearn-train-pytorch-model = "ctlearn.tools.pytorch.train_model:main"
ctlearn-predict-mono-model = "ctlearn.tools.predict_model:mono_tool"
ctlearn-predict-stereo-model = "ctlearn.tools.predict_model:stereo_tool"
ctlearn-predict-LST1= "ctlearn.tools.predict_LST1:main"

[tool.setuptools_scm]
version_file = "ctlearn/_version.py"

[tool.pytest.ini_options]
testpaths = ["ctlearn"]
markers = [
    "verifies_usecase(usecase_id): mark test as verifying a specific use case",
]

norecursedirs = [
    ".git",
    "notebooks",
    "build",
    "scripts",
    "docs",
    "images"
]
