{% set data = load_setup_py_data() %}

package:
  name: ctlearn
  version: { data.get('version') }}
source:
  path: ..
build:
  noarch: generic
  number: '0'
  string: py311_0
requirements:
  build:
    - absl-py 2.1.0 pyhd8ed1ab_0
    - aiohttp 3.9.5 py311h05b510d_0
    - aiosignal 1.3.1 pyhd8ed1ab_0
    - anyio 4.3.0 pyhd8ed1ab_0
    - appnope 0.1.4 pyhd8ed1ab_0
    - argon2-cffi 23.1.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py311heffc1b2_4
    - arrow 1.3.0 pyhd8ed1ab_0
    - astropy 5.3.4 py311h9ea6feb_2
    - asttokens 2.4.1 pyhd8ed1ab_0
    - astunparse 1.6.3 pyhd8ed1ab_0
    - async-lru 2.0.4 pyhd8ed1ab_0
    - attrs 23.2.0 pyh71513ae_0
    - babel 2.14.0 pyhd8ed1ab_0
    - beautifulsoup4 4.12.3 pyha770c72_0
    - bleach 6.1.0 pyhd8ed1ab_0
    - blinker 1.8.2 pyhd8ed1ab_0
    - blosc 1.21.5 hc338f07_0
    - bokeh 2.4.3 pyhd8ed1ab_3
    - brotli 1.1.0 hb547adb_1
    - brotli-bin 1.1.0 hb547adb_1
    - brotli-python 1.1.0 py311ha891d26_1
    - bzip2 1.0.8 h93a5062_5
    - c-ares 1.28.1 h93a5062_0
    - c-blosc2 2.14.4 ha57e6be_1
    - ca-certificates 2024.6.2 hf0a4a13_0
    - cached-property 1.5.2 hd8ed1ab_1
    - cached_property 1.5.2 pyha770c72_1
    - cachetools 5.3.3 pyhd8ed1ab_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - cffi 1.16.0 py311h4a08483_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - click 8.1.7 unix_pyh707e725_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - comm 0.2.2 pyhd8ed1ab_0
    - contourpy 1.2.1 py311hcc98501_0
    - corsikaio 0.3.4 pyh7448d05_0
    - cryptography 42.0.7 py311hcaeb4ce_0
    - ctapipe 0.20.0 pyhd8ed1ab_0
    - cycler 0.12.1 pyhd8ed1ab_0
    - debugpy 1.8.1 py311h92babd0_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - dl1_data_handler 0.11.1 py311_0
    - docutils 0.21.2 pyhd8ed1ab_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - eventio 1.12.1 py311h05b510d_0
    - exceptiongroup 1.2.0 pyhd8ed1ab_2
    - executing 2.0.1 pyhd8ed1ab_0
    - flatbuffers 23.5.26 h13dd4ca_1
    - fonttools 4.53.0 py311hd3f4193_0
    - fqdn 1.5.1 pyhd8ed1ab_0
    - freetype 2.12.1 hadb7bae_2
    - frozenlist 1.4.1 py311h05b510d_0
    - gast 0.5.4 pyhd8ed1ab_0
    - giflib 5.2.2 h93a5062_0
    - google-auth 2.29.0 pyhca7485f_0
    - google-auth-oauthlib 1.2.0 pyhd8ed1ab_0
    - google-pasta 0.2.0 pyh8c360ce_0
    - grpcio 1.59.3 py311hf5d242d_0
    - h11 0.14.0 pyhd8ed1ab_0
    - h2 4.1.0 pyhd8ed1ab_0
    - h5py 3.11.0 nompi_py311hd41bb03_101
    - hdf5 1.14.3 nompi_h751145d_101
    - hpack 4.0.0 pyh9f0ad1d_0
    - httpcore 1.0.5 pyhd8ed1ab_0
    - httpx 0.27.0 pyhd8ed1ab_0
    - hyperframe 6.0.1 pyhd8ed1ab_0
    - icu 73.2 hc8870d7_0
    - idna 3.7 pyhd8ed1ab_0
    - iminuit 2.25.2 py311h92babd0_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - importlib_metadata 7.1.0 hd8ed1ab_0
    - importlib_resources 6.4.0 pyhd8ed1ab_0
    - ipykernel 6.29.3 pyh3cd1d5f_0
    - ipython 8.25.0 pyh707e725_0
    - ipywidgets 8.1.3 pyhd8ed1ab_0
    - isoduration 20.11.0 pyhd8ed1ab_0
    - jedi 0.19.1 pyhd8ed1ab_0
    - jinja2 3.0.3 pyhd8ed1ab_0
    - joblib 1.4.2 pyhd8ed1ab_0
    - json5 0.9.25 pyhd8ed1ab_0
    - jsonpointer 2.4 py311h267d04e_3
    - jsonschema 4.22.0 pyhd8ed1ab_0
    - jsonschema-specifications 2023.12.1 pyhd8ed1ab_0
    - jsonschema-with-format-nongpl 4.22.0 pyhd8ed1ab_0
    - jupyter 1.0.0 pyhd8ed1ab_10
    - jupyter-lsp 2.2.5 pyhd8ed1ab_0
    - jupyter_client 8.6.2 pyhd8ed1ab_0
    - jupyter_console 6.6.3 pyhd8ed1ab_0
    - jupyter_core 5.7.2 py311h267d04e_0
    - jupyter_events 0.10.0 pyhd8ed1ab_0
    - jupyter_server 2.14.1 pyhd8ed1ab_0
    - jupyter_server_terminals 0.5.3 pyhd8ed1ab_0
    - jupyterlab 4.2.1 pyhd8ed1ab_0
    - jupyterlab_pygments 0.3.0 pyhd8ed1ab_1
    - jupyterlab_server 2.27.2 pyhd8ed1ab_0
    - jupyterlab_widgets 3.0.11 pyhd8ed1ab_0
    - keras 2.15.0 pyhd8ed1ab_0
    - kiwisolver 1.4.5 py311he4fd1f5_1
    - krb5 1.21.2 h92f50d5_0
    - lcms2 2.16 ha0e7c42_0
    - lerc 4.0.0 h9a09cb3_0
    - libabseil 20230802.1 cxx17_h13dd4ca_0
    - libaec 1.1.3 hebf3989_0
    - libblas 3.9.0 22_osxarm64_openblas
    - libbrotlicommon 1.1.0 hb547adb_1
    - libbrotlidec 1.1.0 hb547adb_1
    - libbrotlienc 1.1.0 hb547adb_1
    - libcblas 3.9.0 22_osxarm64_openblas
    - libcurl 8.7.1 h2d989ff_0
    - libcxx 17.0.6 h5f092b4_0
    - libdeflate 1.20 h93a5062_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h93a5062_2
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_3
    - libgfortran5 13.2.0 hf226fd6_3
    - libgrpc 1.59.3 h9560976_0
    - libjpeg-turbo 3.0.0 hb547adb_1
    - liblapack 3.9.0 22_osxarm64_openblas
    - libllvm14 14.0.6 hd1a9a77_4
    - libnghttp2 1.58.0 ha4dd798_1
    - libopenblas 0.3.27 openmp_h6c19121_0
    - libpng 1.6.43 h091b4b1_0
    - libprotobuf 4.24.4 h810fc01_0
    - libre2-11 2023.09.01 h741fcf5_1
    - libsodium 1.0.18 h27ca646_1
    - libsqlite 3.45.3 h091b4b1_0
    - libssh2 1.11.0 h7a5bd25_0
    - libtiff 4.6.0 h07db509_3
    - libwebp-base 1.4.0 h93a5062_0
    - libxcb 1.15 hf346824_0
    - libzlib 1.2.13 hfb2fe0b_6
    - llvm-openmp 18.1.6 hde57baf_0
    - llvmlite 0.42.0 py311hf5d242d_1
    - lz4-c 1.9.4 hb7217d7_0
    - markdown 3.6 pyhd8ed1ab_0
    - markupsafe 2.1.5 py311h05b510d_0
    - matplotlib-base 3.8.4 py311h000fb6e_2
    - matplotlib-inline 0.1.7 pyhd8ed1ab_0
    - mistune 3.0.2 pyhd8ed1ab_0
    - ml_dtypes 0.2.0 py311h9e438b8_2
    - multidict 6.0.5 py311he2be06e_0
    - munkres 1.1.4 pyh9f0ad1d_0
    - nbclient 0.10.0 pyhd8ed1ab_0
    - nbconvert 7.16.4 hd8ed1ab_0
    - nbconvert-core 7.16.4 pyhd8ed1ab_0
    - nbconvert-pandoc 7.16.4 hd8ed1ab_0
    - nbformat 5.10.4 pyhd8ed1ab_0
    - ncurses 6.5 hb89a1cb_0
    - nest-asyncio 1.6.0 pyhd8ed1ab_0
    - notebook 7.2.0 pyhd8ed1ab_0
    - notebook-shim 0.2.4 pyhd8ed1ab_0
    - numba 0.59.1 py311h00351ea_0
    - numexpr 2.10.0 py311h4b4568b_0
    - numpy 1.26.4 py311h7125741_0
    - oauthlib 3.2.2 pyhd8ed1ab_0
    - openjpeg 2.5.2 h9f1df11_0
    - openssl 3.3.0 hfb2fe0b_3
    - opt_einsum 3.3.0 pyhc1e730c_2
    - overrides 7.7.0 pyhd8ed1ab_0
    - packaging 24.0 pyhd8ed1ab_0
    - pandas 2.2.2 py311h4b4568b_1
    - pandoc 3.2 hce30654_0
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - parso 0.8.4 pyhd8ed1ab_0
    - pexpect 4.9.0 pyhd8ed1ab_0
    - pickleshare 0.7.5 py_1003
    - pillow 10.3.0 py311h0b5d0a1_0
    - pip 24.0 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_1
    - platformdirs 4.2.2 pyhd8ed1ab_0
    - prometheus_client 0.20.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.42 pyha770c72_0
    - prompt_toolkit 3.0.42 hd8ed1ab_0
    - protobuf 4.24.4 py311h4d1eceb_0
    - psutil 5.9.8 py311h05b510d_0
    - pthread-stubs 0.4 h27ca646_1001
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - py-cpuinfo 9.0.0 pyhd8ed1ab_0
    - pyasn1 0.6.0 pyhd8ed1ab_0
    - pyasn1-modules 0.4.0 pyhd8ed1ab_0
    - pycparser 2.22 pyhd8ed1ab_0
    - pyerfa 2.0.1.4 py311h5d790af_1
    - pygments 2.18.0 pyhd8ed1ab_0
    - pyjwt 2.8.0 pyhd8ed1ab_1
    - pyobjc-core 10.2 py311h665608e_0
    - pyobjc-framework-cocoa 10.2 py311h665608e_0
    - pyopenssl 24.0.0 pyhd8ed1ab_0
    - pyparsing 3.1.2 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - pytables 3.9.2 py311hf4904c8_2
    - python 3.11.0 h3ba56d0_1_cpython
    - python-dateutil 2.9.0 pyhd8ed1ab_0
    - python-fastjsonschema 2.19.1 pyhd8ed1ab_0
    - python-flatbuffers 24.3.25 pyh59ac667_0
    - python-json-logger 2.0.7 pyhd8ed1ab_0
    - python-tzdata 2024.1 pyhd8ed1ab_0
    - python_abi 3.11 4_cp311
    - pytz 2024.1 pyhd8ed1ab_0
    - pyu2f 0.1.5 pyhd8ed1ab_0
    - pyyaml 6.0.1 py311heffc1b2_1
    - pyzmq 26.0.3 py311h9bed540_0
    - qtconsole-base 5.5.2 pyha770c72_0
    - qtpy 2.4.1 pyhd8ed1ab_0
    - re2 2023.09.01 h4cba328_1
    - readline 8.2 h92ec313_1
    - referencing 0.35.1 pyhd8ed1ab_0
    - requests 2.32.3 pyhd8ed1ab_0
    - requests-oauthlib 2.0.0 pyhd8ed1ab_0
    - rfc3339-validator 0.1.4 pyhd8ed1ab_0
    - rfc3986-validator 0.1.1 pyh9f0ad1d_0
    - rpds-py 0.18.1 py311h98c6a39_0
    - rsa 4.9 pyhd8ed1ab_0
    - scikit-learn 1.5.0 py311hbfb48bc_1
    - scipy 1.13.1 py311hceeca8c_0
    - send2trash 1.8.3 pyh31c8845_0
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - snappy 1.1.10 hd04f947_1
    - sniffio 1.3.1 pyhd8ed1ab_0
    - soupsieve 2.5 pyhd8ed1ab_1
    - stack_data 0.6.2 pyhd8ed1ab_0
    - tensorboard 2.15.2 pyhd8ed1ab_0
    - tensorboard-data-server 0.7.0 py311h5fb2c35_1
    - tensorflow 2.15.0 cpu_py311h9b82b1a_2
    - tensorflow-base 2.15.0 cpu_py311he034567_2
    - tensorflow-estimator 2.15.0 cpu_py311hcceb7c1_2
    - termcolor 2.4.0 pyhd8ed1ab_0
    - terminado 0.18.1 pyh31c8845_0
    - threadpoolctl 3.5.0 pyhc1e730c_0
    - tinycss2 1.3.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.4 py311h05b510d_0
    - tqdm 4.66.4 pyhd8ed1ab_0
    - traitlets 5.14.3 pyhd8ed1ab_0
    - types-python-dateutil 2.9.0.20240316 pyhd8ed1ab_0
    - typing-extensions 4.12.1 hd8ed1ab_0
    - typing_extensions 4.12.1 pyha770c72_0
    - typing_utils 0.1.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - uri-template 1.3.0 pyhd8ed1ab_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wcwidth 0.2.13 pyhd8ed1ab_0
    - webcolors 1.13 pyhd8ed1ab_0
    - webencodings 0.5.1 pyhd8ed1ab_2
    - websocket-client 1.8.0 pyhd8ed1ab_0
    - werkzeug 3.0.3 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - widgetsnbextension 4.0.11 pyhd8ed1ab_0
    - wrapt 1.14.1 py311he2be06e_1
    - xorg-libxau 1.0.11 hb547adb_0
    - xorg-libxdmcp 1.1.3 h27ca646_0
    - xz 5.2.6 h57fd34a_0
    - yaml 0.2.5 h3422bc3_2
    - yarl 1.9.4 py311h05b510d_0
    - zeromq 4.3.5 hcc0f68c_4
    - zipp 3.17.0 pyhd8ed1ab_0
    - zlib-ng 2.0.7 h1a8c8d9_0
    - zstandard 0.22.0 py311h67b91a1_0
    - zstd 1.5.5 h4f39d0f_0
  host:
    - absl-py 2.1.0 pyhd8ed1ab_0
    - aiohttp 3.9.5 py311h05b510d_0
    - aiosignal 1.3.1 pyhd8ed1ab_0
    - anyio 4.3.0 pyhd8ed1ab_0
    - appnope 0.1.4 pyhd8ed1ab_0
    - argon2-cffi 23.1.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py311heffc1b2_4
    - arrow 1.3.0 pyhd8ed1ab_0
    - astropy 5.3.4 py311h9ea6feb_2
    - asttokens 2.4.1 pyhd8ed1ab_0
    - astunparse 1.6.3 pyhd8ed1ab_0
    - async-lru 2.0.4 pyhd8ed1ab_0
    - attrs 23.2.0 pyh71513ae_0
    - babel 2.14.0 pyhd8ed1ab_0
    - beautifulsoup4 4.12.3 pyha770c72_0
    - bleach 6.1.0 pyhd8ed1ab_0
    - blinker 1.8.2 pyhd8ed1ab_0
    - blosc 1.21.5 hc338f07_0
    - bokeh 2.4.3 pyhd8ed1ab_3
    - brotli 1.1.0 hb547adb_1
    - brotli-bin 1.1.0 hb547adb_1
    - brotli-python 1.1.0 py311ha891d26_1
    - bzip2 1.0.8 h93a5062_5
    - c-ares 1.28.1 h93a5062_0
    - c-blosc2 2.14.4 ha57e6be_1
    - ca-certificates 2024.6.2 hf0a4a13_0
    - cached-property 1.5.2 hd8ed1ab_1
    - cached_property 1.5.2 pyha770c72_1
    - cachetools 5.3.3 pyhd8ed1ab_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - cffi 1.16.0 py311h4a08483_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - click 8.1.7 unix_pyh707e725_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - comm 0.2.2 pyhd8ed1ab_0
    - contourpy 1.2.1 py311hcc98501_0
    - corsikaio 0.3.4 pyh7448d05_0
    - cryptography 42.0.7 py311hcaeb4ce_0
    - ctapipe 0.20.0 pyhd8ed1ab_0
    - cycler 0.12.1 pyhd8ed1ab_0
    - debugpy 1.8.1 py311h92babd0_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - dl1_data_handler 0.11.1 py311_0
    - docutils 0.21.2 pyhd8ed1ab_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - eventio 1.12.1 py311h05b510d_0
    - exceptiongroup 1.2.0 pyhd8ed1ab_2
    - executing 2.0.1 pyhd8ed1ab_0
    - flatbuffers 23.5.26 h13dd4ca_1
    - fonttools 4.53.0 py311hd3f4193_0
    - fqdn 1.5.1 pyhd8ed1ab_0
    - freetype 2.12.1 hadb7bae_2
    - frozenlist 1.4.1 py311h05b510d_0
    - gast 0.5.4 pyhd8ed1ab_0
    - giflib 5.2.2 h93a5062_0
    - google-auth 2.29.0 pyhca7485f_0
    - google-auth-oauthlib 1.2.0 pyhd8ed1ab_0
    - google-pasta 0.2.0 pyh8c360ce_0
    - grpcio 1.59.3 py311hf5d242d_0
    - h11 0.14.0 pyhd8ed1ab_0
    - h2 4.1.0 pyhd8ed1ab_0
    - h5py 3.11.0 nompi_py311hd41bb03_101
    - hdf5 1.14.3 nompi_h751145d_101
    - hpack 4.0.0 pyh9f0ad1d_0
    - httpcore 1.0.5 pyhd8ed1ab_0
    - httpx 0.27.0 pyhd8ed1ab_0
    - hyperframe 6.0.1 pyhd8ed1ab_0
    - icu 73.2 hc8870d7_0
    - idna 3.7 pyhd8ed1ab_0
    - iminuit 2.25.2 py311h92babd0_0
    - importlib-metadata 7.1.0 pyha770c72_0
    - importlib_metadata 7.1.0 hd8ed1ab_0
    - importlib_resources 6.4.0 pyhd8ed1ab_0
    - ipykernel 6.29.3 pyh3cd1d5f_0
    - ipython 8.25.0 pyh707e725_0
    - ipywidgets 8.1.3 pyhd8ed1ab_0
    - isoduration 20.11.0 pyhd8ed1ab_0
    - jedi 0.19.1 pyhd8ed1ab_0
    - jinja2 3.0.3 pyhd8ed1ab_0
    - joblib 1.4.2 pyhd8ed1ab_0
    - json5 0.9.25 pyhd8ed1ab_0
    - jsonpointer 2.4 py311h267d04e_3
    - jsonschema 4.22.0 pyhd8ed1ab_0
    - jsonschema-specifications 2023.12.1 pyhd8ed1ab_0
    - jsonschema-with-format-nongpl 4.22.0 pyhd8ed1ab_0
    - jupyter 1.0.0 pyhd8ed1ab_10
    - jupyter-lsp 2.2.5 pyhd8ed1ab_0
    - jupyter_client 8.6.2 pyhd8ed1ab_0
    - jupyter_console 6.6.3 pyhd8ed1ab_0
    - jupyter_core 5.7.2 py311h267d04e_0
    - jupyter_events 0.10.0 pyhd8ed1ab_0
    - jupyter_server 2.14.1 pyhd8ed1ab_0
    - jupyter_server_terminals 0.5.3 pyhd8ed1ab_0
    - jupyterlab 4.2.1 pyhd8ed1ab_0
    - jupyterlab_pygments 0.3.0 pyhd8ed1ab_1
    - jupyterlab_server 2.27.2 pyhd8ed1ab_0
    - jupyterlab_widgets 3.0.11 pyhd8ed1ab_0
    - keras 2.15.0 pyhd8ed1ab_0
    - kiwisolver 1.4.5 py311he4fd1f5_1
    - krb5 1.21.2 h92f50d5_0
    - lcms2 2.16 ha0e7c42_0
    - lerc 4.0.0 h9a09cb3_0
    - libabseil 20230802.1 cxx17_h13dd4ca_0
    - libaec 1.1.3 hebf3989_0
    - libblas 3.9.0 22_osxarm64_openblas
    - libbrotlicommon 1.1.0 hb547adb_1
    - libbrotlidec 1.1.0 hb547adb_1
    - libbrotlienc 1.1.0 hb547adb_1
    - libcblas 3.9.0 22_osxarm64_openblas
    - libcurl 8.7.1 h2d989ff_0
    - libcxx 17.0.6 h5f092b4_0
    - libdeflate 1.20 h93a5062_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h93a5062_2
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0 13_2_0_hd922786_3
    - libgfortran5 13.2.0 hf226fd6_3
    - libgrpc 1.59.3 h9560976_0
    - libjpeg-turbo 3.0.0 hb547adb_1
    - liblapack 3.9.0 22_osxarm64_openblas
    - libllvm14 14.0.6 hd1a9a77_4
    - libnghttp2 1.58.0 ha4dd798_1
    - libopenblas 0.3.27 openmp_h6c19121_0
    - libpng 1.6.43 h091b4b1_0
    - libprotobuf 4.24.4 h810fc01_0
    - libre2-11 2023.09.01 h741fcf5_1
    - libsodium 1.0.18 h27ca646_1
    - libsqlite 3.45.3 h091b4b1_0
    - libssh2 1.11.0 h7a5bd25_0
    - libtiff 4.6.0 h07db509_3
    - libwebp-base 1.4.0 h93a5062_0
    - libxcb 1.15 hf346824_0
    - libzlib 1.2.13 hfb2fe0b_6
    - llvm-openmp 18.1.6 hde57baf_0
    - llvmlite 0.42.0 py311hf5d242d_1
    - lz4-c 1.9.4 hb7217d7_0
    - markdown 3.6 pyhd8ed1ab_0
    - markupsafe 2.1.5 py311h05b510d_0
    - matplotlib-base 3.8.4 py311h000fb6e_2
    - matplotlib-inline 0.1.7 pyhd8ed1ab_0
    - mistune 3.0.2 pyhd8ed1ab_0
    - ml_dtypes 0.2.0 py311h9e438b8_2
    - multidict 6.0.5 py311he2be06e_0
    - munkres 1.1.4 pyh9f0ad1d_0
    - nbclient 0.10.0 pyhd8ed1ab_0
    - nbconvert 7.16.4 hd8ed1ab_0
    - nbconvert-core 7.16.4 pyhd8ed1ab_0
    - nbconvert-pandoc 7.16.4 hd8ed1ab_0
    - nbformat 5.10.4 pyhd8ed1ab_0
    - ncurses 6.5 hb89a1cb_0
    - nest-asyncio 1.6.0 pyhd8ed1ab_0
    - notebook 7.2.0 pyhd8ed1ab_0
    - notebook-shim 0.2.4 pyhd8ed1ab_0
    - numba 0.59.1 py311h00351ea_0
    - numexpr 2.10.0 py311h4b4568b_0
    - numpy 1.26.4 py311h7125741_0
    - oauthlib 3.2.2 pyhd8ed1ab_0
    - openjpeg 2.5.2 h9f1df11_0
    - openssl 3.3.0 hfb2fe0b_3
    - opt_einsum 3.3.0 pyhc1e730c_2
    - overrides 7.7.0 pyhd8ed1ab_0
    - packaging 24.0 pyhd8ed1ab_0
    - pandas 2.2.2 py311h4b4568b_1
    - pandoc 3.2 hce30654_0
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - parso 0.8.4 pyhd8ed1ab_0
    - pexpect 4.9.0 pyhd8ed1ab_0
    - pickleshare 0.7.5 py_1003
    - pillow 10.3.0 py311h0b5d0a1_0
    - pip 24.0 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_1
    - platformdirs 4.2.2 pyhd8ed1ab_0
    - prometheus_client 0.20.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.42 pyha770c72_0
    - prompt_toolkit 3.0.42 hd8ed1ab_0
    - protobuf 4.24.4 py311h4d1eceb_0
    - psutil 5.9.8 py311h05b510d_0
    - pthread-stubs 0.4 h27ca646_1001
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - py-cpuinfo 9.0.0 pyhd8ed1ab_0
    - pyasn1 0.6.0 pyhd8ed1ab_0
    - pyasn1-modules 0.4.0 pyhd8ed1ab_0
    - pycparser 2.22 pyhd8ed1ab_0
    - pyerfa 2.0.1.4 py311h5d790af_1
    - pygments 2.18.0 pyhd8ed1ab_0
    - pyjwt 2.8.0 pyhd8ed1ab_1
    - pyobjc-core 10.2 py311h665608e_0
    - pyobjc-framework-cocoa 10.2 py311h665608e_0
    - pyopenssl 24.0.0 pyhd8ed1ab_0
    - pyparsing 3.1.2 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - pytables 3.9.2 py311hf4904c8_2
    - python 3.11.0 h3ba56d0_1_cpython
    - python-dateutil 2.9.0 pyhd8ed1ab_0
    - python-fastjsonschema 2.19.1 pyhd8ed1ab_0
    - python-flatbuffers 24.3.25 pyh59ac667_0
    - python-json-logger 2.0.7 pyhd8ed1ab_0
    - python-tzdata 2024.1 pyhd8ed1ab_0
    - python_abi 3.11 4_cp311
    - pytz 2024.1 pyhd8ed1ab_0
    - pyu2f 0.1.5 pyhd8ed1ab_0
    - pyyaml 6.0.1 py311heffc1b2_1
    - pyzmq 26.0.3 py311h9bed540_0
    - qtconsole-base 5.5.2 pyha770c72_0
    - qtpy 2.4.1 pyhd8ed1ab_0
    - re2 2023.09.01 h4cba328_1
    - readline 8.2 h92ec313_1
    - referencing 0.35.1 pyhd8ed1ab_0
    - requests 2.32.3 pyhd8ed1ab_0
    - requests-oauthlib 2.0.0 pyhd8ed1ab_0
    - rfc3339-validator 0.1.4 pyhd8ed1ab_0
    - rfc3986-validator 0.1.1 pyh9f0ad1d_0
    - rpds-py 0.18.1 py311h98c6a39_0
    - rsa 4.9 pyhd8ed1ab_0
    - scikit-learn 1.5.0 py311hbfb48bc_1
    - scipy 1.13.1 py311hceeca8c_0
    - send2trash 1.8.3 pyh31c8845_0
    - setuptools 70.0.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - snappy 1.1.10 hd04f947_1
    - sniffio 1.3.1 pyhd8ed1ab_0
    - soupsieve 2.5 pyhd8ed1ab_1
    - stack_data 0.6.2 pyhd8ed1ab_0
    - tensorboard 2.15.2 pyhd8ed1ab_0
    - tensorboard-data-server 0.7.0 py311h5fb2c35_1
    - tensorflow 2.15.0 cpu_py311h9b82b1a_2
    - tensorflow-base 2.15.0 cpu_py311he034567_2
    - tensorflow-estimator 2.15.0 cpu_py311hcceb7c1_2
    - termcolor 2.4.0 pyhd8ed1ab_0
    - terminado 0.18.1 pyh31c8845_0
    - threadpoolctl 3.5.0 pyhc1e730c_0
    - tinycss2 1.3.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.4 py311h05b510d_0
    - tqdm 4.66.4 pyhd8ed1ab_0
    - traitlets 5.14.3 pyhd8ed1ab_0
    - types-python-dateutil 2.9.0.20240316 pyhd8ed1ab_0
    - typing-extensions 4.12.1 hd8ed1ab_0
    - typing_extensions 4.12.1 pyha770c72_0
    - typing_utils 0.1.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - uri-template 1.3.0 pyhd8ed1ab_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wcwidth 0.2.13 pyhd8ed1ab_0
    - webcolors 1.13 pyhd8ed1ab_0
    - webencodings 0.5.1 pyhd8ed1ab_2
    - websocket-client 1.8.0 pyhd8ed1ab_0
    - werkzeug 3.0.3 pyhd8ed1ab_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - widgetsnbextension 4.0.11 pyhd8ed1ab_0
    - wrapt 1.14.1 py311he2be06e_1
    - xorg-libxau 1.0.11 hb547adb_0
    - xorg-libxdmcp 1.1.3 h27ca646_0
    - xz 5.2.6 h57fd34a_0
    - yaml 0.2.5 h3422bc3_2
    - yarl 1.9.4 py311h05b510d_0
    - zeromq 4.3.5 hcc0f68c_4
    - zipp 3.17.0 pyhd8ed1ab_0
    - zlib-ng 2.0.7 h1a8c8d9_0
    - zstandard 0.22.0 py311h67b91a1_0
    - zstd 1.5.5 h4f39d0f_0
  run:
    - astropy
    - ctapipe ==0.20.0
    - dl1_data_handler ==0.11.1
    - jupyter
    - numpy >=1.20
    - pandas
    - pytables >=3.8
    - python ==3.11
    - scipy
    - tensorflow ==2.15
  test:
    - imports
about:
  home: https://github.com/ctlearn-project/ctlearn/
  license: BSD3-Clause
  license_file: LICENSE
  summary: Deep Learning for IACT Event Reconstruction.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - TjarkMiener
    - nietootein
